spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.com.restosync=${APP_LOG_LEVEL:INFO}
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN
springdoc.api-docs.enabled=${SPRINGDOC_ENABLED:false}
springdoc.swagger-ui.enabled=${SPRINGDOC_ENABLED:false}
